# Generated by Django 5.2.7 on 2026-01-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoItem',
        ),
    ]
