# Generated by Django 5.2.7 on 2026-02-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='firebase_uid',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
