# Generated by Django 5.2.7 on 2026-02-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userinformation_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={'ordering': ['name'], 'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
    ]
