# Generated by Django 5.2.7 on 2026-03-04 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userinformation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_lessons_target', models.PositiveSmallIntegerField(default=1)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Every Day'), ('weekdays', 'Weekdays'), ('weekly', 'Once a Week')], default='weekly', max_length=16)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_preferences', to='users.userinformation')),
            ],
        ),
    ]
