# Generated by Django 5.2.7 on 2026-03-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_learningpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('lesson', 'Lesson'), ('progress', 'Progress'), ('daily_goal', 'Daily Goal'), ('streak', 'Streak'), ('volume', 'Volume')], max_length=32)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinformation',
            name='current_activity_streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='current_goal_streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='last_goal_met_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='total_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='total_correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.userinformation')),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
