"""
Django settings for hebrew project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import dotenv_values, load_dotenv


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "t", "yes", "y", "on"}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (next to manage.py), not only the shell cwd.
# utf-8-sig strips a UTF-8 BOM so the first variable is still recognized on Windows editors.
_ENV_PATH = BASE_DIR / ".env"
load_dotenv(_ENV_PATH, encoding="utf-8-sig")

# If something prevented the vars above from sticking, merge Firebase-related keys explicitly.
if _ENV_PATH.is_file():
    _raw = dotenv_values(_ENV_PATH, encoding="utf-8-sig")
    for _key in ("GOOGLE_APPLICATION_CREDENTIALS", "FIREBASE_CREDENTIALS_JSON"):
        _val = _raw.get(_key)
        if _val and str(_val).strip() and not os.getenv(_key):
            os.environ[_key] = str(_val).strip().strip('"').strip("'")


def _bootstrap_firebase_admin_credentials():
    """Local dev helper: use service account JSON in config/ if env is still unset."""
    if os.getenv("FIREBASE_CREDENTIALS_JSON") or os.getenv("GOOGLE_APPLICATION_CREDENTIALS"):
        return
    _config_dir = BASE_DIR / "config"
    if not _config_dir.is_dir():
        return
    _matches = sorted(_config_dir.glob("*firebase-adminsdk*.json"))
    if _matches:
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(_matches[0].resolve())


_bootstrap_firebase_admin_credentials()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Render (and similar) terminate TLS at the proxy; trust X-Forwarded-Proto for HTTPS/cookies/CSRF.
if env_bool("RENDER", False) or env_bool("DJANGO_USE_PROXY_SSL", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

_csrf_trusted = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").strip()
if _csrf_trusted:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(",") if o.strip()]

if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is required")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'users',
    'main',
    'bible',
    'lessons',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hebrew.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hebrew.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# When DATABASE_URL is set (e.g. on Render with Neon/Supabase), use PostgreSQL.
# Otherwise use SQLite for local development.

if os.getenv("DATABASE_URL"):
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.config(conn_max_age=600, conn_health_checks=True),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

EMAIL_HOST = os.getenv('EMAIL_HOST', '')
# Use console backend when SMTP is not configured (dev) - emails print to terminal
EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
    if not EMAIL_HOST
    else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@example.com')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
