# Generated by Django 5.2.7 on 2026-02-17 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblebook',
            options={'ordering': ['order'], 'verbose_name': 'Bible Book', 'verbose_name_plural': 'Bible Books'},
        ),
        migrations.AlterModelOptions(
            name='biblechapter',
            options={'ordering': ['book__order', 'number'], 'verbose_name': 'Bible Chapter', 'verbose_name_plural': 'Bible Chapters'},
        ),
        migrations.AlterModelOptions(
            name='bibleverse',
            options={'ordering': ['chapter__book__order', 'chapter__number', 'number'], 'verbose_name': 'Bible Verse', 'verbose_name_plural': 'Bible Verses'},
        ),
    ]
