# Generated by Django 5.2.7 on 2026-02-05 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveSmallIntegerField()),
                ('user_answer_json', models.JSONField()),
                ('correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lessons.lessonsession')),
            ],
        ),
    ]
