# Generated by Django 5.2.7 on 2026-02-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HebrewLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('letter', models.CharField(max_length=5)),
                ('name_en', models.CharField(max_length=50)),
                ('transliteration', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
