# Generated by Django 5.2.7 on 2026-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_hebrewletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='seed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonsession',
            name='question_set_json',
            field=models.JSONField(default=list),
        ),
    ]
