# Generated by Django 5.2.7 on 2026-02-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_passes_required_lessonsession_passed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hebrewletter',
            options={'ordering': ['order'], 'verbose_name': 'Hebrew Letter', 'verbose_name_plural': 'Hebrew Letters'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonanswer',
            options={'ordering': ['session', 'question_index', '-answered_at'], 'verbose_name': 'Lesson Answer', 'verbose_name_plural': 'Lesson Answers'},
        ),
        migrations.AlterModelOptions(
            name='lessonsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Lesson Session', 'verbose_name_plural': 'Lesson Sessions'},
        ),
        migrations.AddField(
            model_name='hebrewletter',
            name='dagesh_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lessonanswer',
            name='correct',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lessonsession',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lessonsession',
            name='user_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='lessonanswer',
            index=models.Index(fields=['session', 'correct'], name='lessons_les_session_b94e94_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonanswer',
            index=models.Index(fields=['session', 'question_index', 'correct'], name='lessons_les_session_00243f_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['user_id', 'lesson', 'completed'], name='lessons_les_user_id_645db2_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonsession',
            index=models.Index(fields=['user_id', 'completed', 'passed'], name='lessons_les_user_id_163970_idx'),
        ),
    ]
