# Generated by Django 5.2.7 on 2026-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_hebrewletter_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HebrewVowel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=50)),
                ('transliteration', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hebrew Vowel',
                'verbose_name_plural': 'Hebrew Vowels',
                'ordering': ['order'],
            },
        ),
    ]
