# Generated by GPT: Add HebrewAspectForm and seed aspect lesson/forms

from django.db import migrations, models


def seed_aspect(apps, schema_editor):
    Lesson = apps.get_model("lessons", "Lesson")
    HebrewAspectForm = apps.get_model("lessons", "HebrewAspectForm")

    Lesson.objects.update_or_create(
        slug="aspect-1",
        defaults={"title": "Lesson 4: Aspect", "order": 4, "passes_required": 4},
    )

    rows = [
        # order, aspect, person, gender, number, prefix, suffix, gloss
        # Imperfect
        (1, "imperfect", 3, "m", "singular", "י", "", "he"),
        (2, "imperfect", 3, "m", "plural", "י", "ו", "they"),
        (3, "imperfect", 3, "f", "singular", "ת", "", "she"),
        (4, "imperfect", 3, "f", "plural", "ת", "נה", "they"),
        (5, "imperfect", 2, "m", "singular", "ת", "", "you"),
        (6, "imperfect", 2, "m", "plural", "ת", "ו", "you/y'all"),
        (7, "imperfect", 2, "f", "singular", "ת", "י", "you"),
        (8, "imperfect", 2, "f", "plural", "ת", "נה", "you/y'all"),
        (9, "imperfect", 1, "c", "singular", "א", "", "I"),
        (10, "imperfect", 1, "c", "plural", "נ", "", "we"),
        # Perfect
        (11, "perfect", 3, "m", "singular", "", "", "he"),
        (12, "perfect", 3, "m", "plural", "", "ו", "they"),
        (13, "perfect", 3, "f", "singular", "", "ה", "she"),
        (14, "perfect", 3, "f", "plural", "", "ו", "they"),
        (15, "perfect", 2, "m", "singular", "", "ת", "you"),
        (16, "perfect", 2, "m", "plural", "", "תם", "you/y'all"),
        (17, "perfect", 2, "f", "singular", "", "ת", "you"),
        (18, "perfect", 2, "f", "plural", "", "תן", "you/y'all"),
        (19, "perfect", 1, "c", "singular", "", "תי", "I"),
        (20, "perfect", 1, "c", "plural", "", "נו", "we"),
    ]

    for order, aspect, person, gender, number, prefix, suffix, gloss in rows:
        HebrewAspectForm.objects.update_or_create(
            order=order,
            defaults={
                "aspect": aspect,
                "person": person,
                "gender": gender,
                "number": number,
                "prefix": prefix,
                "suffix": suffix,
                "gloss": gloss,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_hebrewvowel"),
    ]

    operations = [
        migrations.CreateModel(
            name="HebrewAspectForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(unique=True)),
                ("aspect", models.CharField(choices=[("imperfect", "Imperfect"), ("perfect", "Perfect")], max_length=16)),
                ("person", models.PositiveSmallIntegerField()),
                ("gender", models.CharField(choices=[("m", "Masculine"), ("f", "Feminine"), ("c", "Common")], max_length=1)),
                ("number", models.CharField(choices=[("singular", "Singular"), ("plural", "Plural")], max_length=8)),
                ("prefix", models.CharField(blank=True, default="", max_length=8)),
                ("suffix", models.CharField(blank=True, default="", max_length=8)),
                ("gloss", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Hebrew Aspect Form",
                "verbose_name_plural": "Hebrew Aspect Forms",
                "ordering": ["order"],
            },
        ),
        migrations.RunPython(seed_aspect, noop),
    ]

