# Generated by GPT: add vowelled pattern field to HebrewAspectForm

from django.db import migrations, models


def populate_patterns(apps, schema_editor):
    HebrewAspectForm = apps.get_model("lessons", "HebrewAspectForm")

    rows = [
        # order -> pattern (with niqqud where applicable)
        # Imperfect (prefix conjugation)
        (1, "יִ___"),        # 3ms
        (2, "יִ___וּ"),      # 3mp
        (3, "תִ___"),        # 3fs
        (4, "תִ___נָה"),     # 3fp
        (5, "תִ___"),        # 2ms
        (6, "תִ___וּ"),      # 2mp
        (7, "תִ___ִי"),      # 2fs
        (8, "תִ___נָה"),     # 2fp
        (9, "אֶ___"),        # 1cs
        (10, "נִ___"),       # 1cp
        # Perfect (suffix conjugation)
        (11, "___"),         # 3ms
        (12, "___וּ"),       # 3mp
        (13, "___ָה"),       # 3fs
        (14, "___וּ"),       # 3fp (as in your chart)
        (15, "___תָ"),       # 2ms
        (16, "___תֶם"),      # 2mp
        (17, "___תְ"),       # 2fs
        (18, "___תֶן"),      # 2fp
        (19, "___תִי"),      # 1cs
        (20, "___נוּ"),      # 1cp
    ]

    for order, pattern in rows:
        HebrewAspectForm.objects.filter(order=order).update(pattern=pattern)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0010_hebrewaspectform_and_aspect_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="hebrewaspectform",
            name="pattern",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.RunPython(populate_patterns, noop),
    ]

