# Generated by GPT: add pronominal suffix lesson data

from django.db import migrations, models


def seed_suffixes(apps, schema_editor):
    Lesson = apps.get_model("lessons", "Lesson")
    HebrewPronominalSuffix = apps.get_model("lessons", "HebrewPronominalSuffix")

    Lesson.objects.update_or_create(
        slug="suffixes-1",
        defaults={"title": "Lesson 5: Pronominal Suffixes", "order": 5, "passes_required": 4},
    )

    rows = [
        # order, person, gender, number, pattern, gloss
        (1, 3, "m", "singular", "___וֹ", "him/his"),
        (2, 3, "m", "singular", "___הוּ", "him/his"),
        (3, 3, "m", "plural", "___ם", "them/their"),
        (4, 3, "m", "plural", "___הֶם", "them/their"),
        (5, 3, "f", "singular", "___הּ", "her/her"),
        (6, 3, "f", "singular", "___נָה", "her/her"),
        (7, 3, "f", "plural", "___ן", "them/their"),
        (8, 3, "f", "plural", "___הֶן", "them/their"),
        (9, 2, "m", "singular", "___ךָ", "you/your"),
        (10, 2, "m", "plural", "___כֶם", "you/your"),
        (11, 2, "f", "singular", "___ךְ", "you/your"),
        (12, 2, "f", "plural", "___כֶן", "you/your"),
        (13, 1, "c", "singular", "___י", "me/my"),
        (14, 1, "c", "plural", "___נוּ", "us/our"),
    ]

    for order, person, gender, number, pattern, gloss in rows:
        HebrewPronominalSuffix.objects.update_or_create(
            order=order,
            defaults={
                "person": person,
                "gender": gender,
                "number": number,
                "pattern": pattern,
                "gloss": gloss,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0011_hebrewaspectform_pattern"),
    ]

    operations = [
        migrations.CreateModel(
            name="HebrewPronominalSuffix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(unique=True)),
                ("person", models.PositiveSmallIntegerField()),
                ("gender", models.CharField(choices=[("m", "Masculine"), ("f", "Feminine"), ("c", "Common")], max_length=1)),
                ("number", models.CharField(choices=[("singular", "Singular"), ("plural", "Plural")], max_length=8)),
                ("pattern", models.CharField(max_length=32)),
                ("gloss", models.CharField(max_length=24)),
            ],
            options={
                "verbose_name": "Hebrew Pronominal Suffix",
                "verbose_name_plural": "Hebrew Pronominal Suffixes",
                "ordering": ["order"],
            },
        ),
        migrations.RunPython(seed_suffixes, noop),
    ]

