# Generated by GPT: add prepositions lesson data

from django.db import migrations, models


def seed_prepositions(apps, schema_editor):
    Lesson = apps.get_model("lessons", "Lesson")
    HebrewPreposition = apps.get_model("lessons", "HebrewPreposition")

    Lesson.objects.update_or_create(
        slug="prepositions-1",
        defaults={"title": "Lesson 6: Prepositions", "order": 6, "passes_required": 4},
    )

    rows = [
        # order, kind, form, meaning, notes
        (1, "inseparable", "בְּ", "in/by/with", ""),
        (2, "inseparable", "לְ", "to/toward", ""),
        (3, "inseparable", "כְּ", "like/as", ""),
        (4, "inseparable", "הַ", "the", "article"),
        (5, "inseparable", "בַ", "prep. + the", "contracted form"),
        (6, "separable", "מִן", "from/of", ""),
        (7, "separable", "מֵ", "from/of", "before some sounds"),
        (8, "independent", "אֶל", "to/toward", ""),
        (9, "independent", "עַל", "on/over", ""),
        (10, "independent", "אֵת", "with", ""),
        (11, "independent", "תַּחַת", "under", ""),
        (12, "independent", "עִם", "with", ""),
        (13, "independent", "בֵּין", "between", ""),
    ]

    for order, kind, form, meaning, notes in rows:
        HebrewPreposition.objects.update_or_create(
            order=order,
            defaults={
                "kind": kind,
                "form": form,
                "meaning": meaning,
                "notes": notes,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0012_hebrewpronominalsuffix_and_lesson5"),
    ]

    operations = [
        migrations.CreateModel(
            name="HebrewPreposition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(unique=True)),
                ("kind", models.CharField(choices=[("inseparable", "Inseparable"), ("separable", "Separable"), ("independent", "Independent")], max_length=16)),
                ("form", models.CharField(max_length=24)),
                ("meaning", models.CharField(max_length=48)),
                ("notes", models.CharField(blank=True, default="", max_length=80)),
            ],
            options={
                "verbose_name": "Hebrew Preposition",
                "verbose_name_plural": "Hebrew Prepositions",
                "ordering": ["order"],
            },
        ),
        migrations.RunPython(seed_prepositions, noop),
    ]

